// Code generated by optiongen. DO NOT EDIT.
// optiongen: github.com/timestee/optiongen

package example

import (
	"sync/atomic"
	"unsafe"
)

// HTTP parsing and communication with DNS resolver was successful, and the response body content is a DNS response in either binary or JSON encoding,
// depending on the query endpoint, Accept header and GET parameters.

// spec struct
type spec struct {
	// test comment 5
	// test comment 6
	// annotation@TestNil1(comment="method commnet", private="true", xconf="test_nil1")
	TestNil1       interface{} `xconf:"test_nil1"`  // test comment 1
	TestBool1      bool        `xconf:"test_bool1"` // test comment 2
	TestInt1       int         `xconf:"test_int1"`
	TestNilFunc1   func()      `xconf:"test_nil_func1"`  // 中文2
	TestReserved2_ []byte      `xconf:"test_reserved2_"` // sql.DB对外暴露出了其运行时的状态db.DBStats，sql.DB在关闭，创建，释放连接时候，会维护更新这个状态。
	// 我们可以通过prometheus来收集连接池状态，然后在grafana面板上配置指标，使指标可以动态的展示。
	TestReserved2Inner1 int `xconf:"test_reserved2_inner1"`
}

// ApplyOption apply mutiple new option
func (cc *spec) ApplyOption(opts ...SpecOption) {
	for _, opt := range opts {
		opt(cc)
	}
}

// SpecOption option func
type SpecOption func(cc *spec)

// WithServerTestBool1 option func for TestBool1
func WithServerTestBool1(v bool) SpecOption {
	return func(cc *spec) {
		cc.TestBool1 = v
	}
}

// 这里是函数注释3
// 这里是函数注释4
// WithServerTestInt1 option func for TestInt1
func WithServerTestInt1(v int) SpecOption {
	return func(cc *spec) {
		cc.TestInt1 = v
	}
}

// WithServerTestNilFunc1 option func for TestNilFunc1
func WithServerTestNilFunc1(v func()) SpecOption {
	return func(cc *spec) {
		cc.TestNilFunc1 = v
	}
}

// WithServerTestReserved2Inner1 option func for TestReserved2Inner1
func WithServerTestReserved2Inner1(v int) SpecOption {
	return func(cc *spec) {
		cc.TestReserved2Inner1 = v
	}
}

// NewSpec(opts... SpecOption) new spec
func NewSpec(opts ...SpecOption) *spec {
	cc := newDefaultSpec()

	for _, opt := range opts {
		opt(cc)
	}
	if watchDogSpec != nil {
		watchDogSpec(cc)
	}
	return cc
}

// InstallSpecWatchDog the installed func will called when NewSpec(opts... SpecOption)  called
func InstallSpecWatchDog(dog func(cc *spec)) {
	watchDogSpec = dog
}

// watchDogSpec global watch dog
var watchDogSpec func(cc *spec)

// newDefaultSpec new default spec
func newDefaultSpec() *spec {
	cc := &spec{
		TestNil1:       nil,
		TestReserved2_: nil,
	}

	for _, opt := range [...]SpecOption{
		WithServerTestBool1(false),
		WithServerTestInt1(32),
		WithServerTestNilFunc1(nil),
		WithServerTestReserved2Inner1(1),
	} {
		opt(cc)
	}

	return cc
}

// AtomicSetFunc used for XConf
func (cc *spec) AtomicSetFunc() func(interface{}) { return AtomicSpecSet }

// atomicspec global *spec holder
var atomicSpec unsafe.Pointer

// AtomicSpecSet atomic setter for *spec
func AtomicSpecSet(update interface{}) {
	atomic.StorePointer(&atomicSpec, (unsafe.Pointer)(update.(*spec)))
}

// AtomicSpec return atomic *spec visitor
func AtomicSpec() SpecVisitor {
	current := (*spec)(atomic.LoadPointer(&atomicSpec))
	if current == nil {
		atomic.CompareAndSwapPointer(&atomicSpec, nil, (unsafe.Pointer)(newDefaultSpec()))
		return (*spec)(atomic.LoadPointer(&atomicSpec))
	}
	return current
}

// all getter func
// GetTestNil1 return struct field: TestNil1
func (cc *spec) GetTestNil1() interface{} { return cc.TestNil1 }

// GetTestBool1 return struct field: TestBool1
func (cc *spec) GetTestBool1() bool { return cc.TestBool1 }

// GetTestInt1 return struct field: TestInt1
func (cc *spec) GetTestInt1() int { return cc.TestInt1 }

// GetTestNilFunc1 return struct field: TestNilFunc1
func (cc *spec) GetTestNilFunc1() func() { return cc.TestNilFunc1 }

// GetTestReserved2_ return struct field: TestReserved2_
func (cc *spec) GetTestReserved2_() []byte { return cc.TestReserved2_ }

// GetTestReserved2Inner1 return struct field: TestReserved2Inner1
func (cc *spec) GetTestReserved2Inner1() int { return cc.TestReserved2Inner1 }

// SpecVisitor visitor interface for spec
type SpecVisitor interface {
	GetTestNil1() interface{}
	GetTestBool1() bool
	GetTestInt1() int
	GetTestNilFunc1() func()
	GetTestReserved2_() []byte
	GetTestReserved2Inner1() int
}

type SpecInterface interface {
	SpecVisitor
	ApplyOption(...SpecOption) []SpecOption
}
